### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by elfmimi** [jacobrosenthal/hf2-rs#18]
Currently it fails to compile on Windows.

The way cargo-flash deals with the same problem looks simple and nice.

https://github.com/probe-rs/cargo-flash/blob/ee858ce571c3cb6d421e35986f441c161d18ff3a/src/main.rs#L230-L232

https://github.com/probe-rs/cargo-flash/blob/ee858ce571c3cb6d421e35986f441c161d18ff3a/src/main.rs#L516-L527

cf. https://github.com/jacobrosenthal/hf2-rs/pull/8

**Comment by jacobrosenthal** [comment]
Sounds good. Can you test and PR fixes? Ill happily merge
