### ISSUE TITLE
Add Wio Terminal to vid/pid database

### ISSUE THREAD

**Issue by twitchyliquid64** [jacobrosenthal/hf2-rs#31]
Could this VID/PID pair be [added](https://github.com/jacobrosenthal/hf2-rs/blob/aac1b2518ec86ef165bfb7f71ea9b1a90893ed3e/hf2/src/utils/mod.rs#L191)?

```
vid 0x2886
pid 0x002d
```

Tested successfully with: `cargo hf2 --release --example=orientation --vid 0x2886 --pid 0x002d`

And these udev rules:

```
ATTRS{idVendor}=="2886", ATTRS{idProduct}=="002d", ENV{ID_MM_DEVICE_IGNORE}="1"
SUBSYSTEM=="usb", ATTRS{idVendor}=="2886", ATTRS{idProduct}=="002d", MODE="0666"
SUBSYSTEM=="tty", ATTRS{idVendor}=="2886", ATTRS{idProduct}=="002d", MODE="0666"
```

Thanks!

**Comment by twitchyliquid64** [comment]
Btw, this is the Seeed studio Wio Terminal version 1: https://www.seeedstudio.com/Wio-Terminal-p-4509.html

**Comment by jacobrosenthal** [comment]
Do you know what repo theyre developing these in. Id like to take any more vids and pids they have and have a link to check to stay current

**Comment by twitchyliquid64** [comment]
I havent seen any repo for the UF2 bootloader used. We (jesse) are working on a BSP at https://github.com/jessebraham/wio-terminal, but eventually want to bring it into atsamd.

I dont have any other board so I can't determine the other PIDs.

**Comment by twitchyliquid64** [comment]
Ooooo, found some stuff

https://github.com/macky-n-tosh/Arduino_ref/blob/899fe0810a07bff6f05ac42eec72ab60a90505db/packages/Seeeduino/hardware/samd/1.7.7/boards.txt#L27

https://github.com/platformio/platform-atmelsam/blob/0ed89cea0a96ce960279e34c9f4fb763e728fbcd/boards/seeed_wio_terminal.json#L18
