### ISSUE TITLE
cargo-hf2 fails to compile on Windows 

### ISSUE THREAD

**Issue by codytrey** [jacobrosenthal/hf2-rs#7]
Compiling cargo-hf2 v0.1.0
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> C:\Users\cbelcher\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-hf2-0.1.0\src\main.rs:79:22
   |
79 |         use std::os::unix::process::ExitStatusExt;
   |                      ^^^^ could not find `unix` in `os`

error[E0599]: no method named `signal` found for type `std::process::ExitStatus` in the current scope
  --> C:\Users\cbelcher\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-hf2-0.1.0\src\main.rs:82:48
   |
82 |             .or_else(|| if cfg!(unix) { status.signal() } else { None })
   |                                                ^^^^^^ method not found in `std::process::ExitStatus`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: failed to compile `cargo-hf2 v0.1.0`, intermediate artifacts can be found at `C:\Users\cbelcher\AppData\Local\Temp\cargo-installZZNR1I`

Caused by:
  could not compile `cargo-hf2`.

To learn more, run the command again with --verbose.

**Comment by jacobrosenthal** [comment]
Closed by #20
